export const GET_CLIENT_INFO = "GET_CLIENT_INFO";
export const SET_SENDER_INFO = "SET_SENDER_INFO";
export const GET_CLIENT_LIST = "GET_CLIENT_LIST";
export const REMOVE_CLIENT_LIST = "REMOVE_CLIENT_LIST";
